/**
 * GraphQL Schema Registry
 *
 * This file provides a registry of all modular GraphQL schema files.
 * The schemas are automatically generated from NestJS GraphQL decorators.
 *
 * Usage:
 * 1. Main schema (schema.gql) is auto-generated by NestJS and used by Apollo Server
 * 2. Individual module schemas are split for organization and reference
 * 3. Run `npm run schema:split` to regenerate modular schemas
 *
 * Note: All .gql files are auto-generated. Do not manually edit them.
 */

import { join } from 'path';

export const SCHEMA_DIR = join(process.cwd(), 'src/graphql/schemas');

export const SCHEMA_FILES = {
    // Main schema file used by Apollo Server
    main: join(SCHEMA_DIR, 'schema.gql'),

    // Module-specific schema files (for reference)
    auth: join(SCHEMA_DIR, 'auth.gql'),
    users: join(SCHEMA_DIR, 'users.gql'),
    roles: join(SCHEMA_DIR, 'roles.gql'),
    permissions: join(SCHEMA_DIR, 'permissions.gql'),
    countries: join(SCHEMA_DIR, 'countries.gql'),
    states: join(SCHEMA_DIR, 'states.gql'),
    cities: join(SCHEMA_DIR, 'cities.gql'),
    masterData: join(SCHEMA_DIR, 'master-data.gql'),
    profiles: join(SCHEMA_DIR, 'profiles.gql'),
    subscriptionPlans: join(SCHEMA_DIR, 'subscription-plans.gql'),
    userSubscriptions: join(SCHEMA_DIR, 'user-subscriptions.gql'),
    payments: join(SCHEMA_DIR, 'payments.gql'),
    promoCodes: join(SCHEMA_DIR, 'promo-codes.gql'),
    userVouchers: join(SCHEMA_DIR, 'user-vouchers.gql'),
    supportTickets: join(SCHEMA_DIR, 'support-tickets.gql'),
    supportMessages: join(SCHEMA_DIR, 'support-messages.gql'),
    profileReports: join(SCHEMA_DIR, 'profile-reports.gql'),
    userProfilePreferences: join(SCHEMA_DIR, 'user-profile-preferences.gql'),
    common: join(SCHEMA_DIR, 'common.gql'),
} as const;

export type SchemaFileKey = keyof typeof SCHEMA_FILES;
