import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import LayoutTheme from "@/components/layout-theme";
import dynamic from 'next/dynamic';
import SEO from '../components/seo';
import DisableConsoleProvider from "@/components/DisableConsoleProvider";
import { RouteLoadingProvider } from "@/components/RouteLoadingProvider";
import ApolloProvider from "@/components/ApolloProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Example: dynamically import a heavy component
// const HeavyComponent = dynamic(() => import('./components/HeavyComponent'), { ssr: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* 🌟 Inject color theme immediately from cookie */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // Read color theme from cookie
                  var cookies = document.cookie.split(';');
                  var theme = 'default';
                  for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.startsWith('color-theme=')) {
                      theme = decodeURIComponent(cookie.substring('color-theme='.length));
                      break;
                    }
                  }
                  document.documentElement.setAttribute('data-theme', theme);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <DisableConsoleProvider />
        <SEO />
        <LayoutTheme defaultTheme="dark">
          <ApolloProvider>
            <RouteLoadingProvider>
              {children}
            </RouteLoadingProvider>
          </ApolloProvider>
        </LayoutTheme>
      </body>
    </html>
  );
}
